name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake lcov cppcheck
        git submodule update --init

    - name: Build with ThreadSanitizer
      run: |
        ./.github/workflows/build_with_tsan.sh

    - name: Run unit tests with coverage
      run: |
        ./.github/workflows/lcov.sh

    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./

    - name: Run static analysis with Cppcheck
      run: |
        cppcheck --suppressions-list=.github/workflows/suppressions.txt  --enable=all --inconclusive --std=c++11 -i ./tests/googletest/ --suppress=missingIncludeSystem .

    - name: Run ThreadSanitizer tests
      run: |
        ./.github/workflows/analyze_with_tsan.sh
